### ISSUE TITLE
The performance decay

### ISSUE THREAD

**Issue by tangsanli5201** [caiqi/mean-teacher-cross-domain-detection#1]
Hi. I got a problem that when we use the proposed mean teacher in (MTOR) in the unsupervised domain adaptation task. I found that the the student performance will increase at the beginning but decrease after training some several epochs (maybe 2). Do you meet the same problem? 
Looking forward to your response. Sincerely.

**Comment by caiqi** [comment]
@tangsanli5201  We also observed similar phenomenons where the performance increases and then drops slightly during the training process. However, the performance becomes stable in the late stage of training and we report the performance of the final epoch.
